server:
  port: 8768
spring:
  application:
    name: zuul-proxy
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  add-host-header: true
  sensitive-headers:
    - Cookie
    - Set-Cookie
    - Authorization
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 10000
  routes:
    fegin-service:
      path: /fignService/**
    SayHello:
      path: /sayService/**
  ignored-services:
    - fegin-service
    - SayHello
#查看路由信息
management:
  endpoints:
    web:
      exposure:
        include:
          - routes
jwt:
  tokenHeader: Authorization
  secret: 823923
  expiration: 86400
  tokenHead: Bearer
  refreshTime: 60
secure:
  ignored:
    urls: #安全路径白名单
      - /admin/login
      - /view/all
      - /swagger-ui.html
      - /webjars/**
      - /swagger-resources/**
      - /error
      - /fignService/say

