server:
  port: 8764
spring:
  application:
    name: fegin-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true #在Feign中开启Hystrix
management:
  endpoints:
    web:
      exposure:
        include:
          - hystrix.stream
          - '*'
  endpoint:
    health:
      show-details: always