server:
  port: 8770
spring:
  application:
    name: admin-client
  boot:
    admin:
      client:
        url: http://localhost:8769
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
logging:
  file: admin-client.log
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
